// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using БазаДанныхИсправленная.Classes;

#nullable disable

namespace БазаДанныхИсправленная.Migrations
{
    [DbContext(typeof(UserDataContext))]
    [Migration("20240329080748_NumberOfClasses")]
    partial class NumberOfClasses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("БазаДанныхИсправленная.Classes.NumberOfClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_Number_Class");

                    b.Property<int>("NumberClass")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Number_of_class");

                    b.Property<int>("TasksId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_Of_Tasks");

                    b.HasKey("Id");

                    b.ToTable("NumberOfClasses", (string)null);
                });

            modelBuilder.Entity("БазаДанныхИсправленная.Classes.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Login");

                    b.Property<int>("NumberOfClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Number_of_class_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
